version: '3.8'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./www:/usr/share/nginx/html
      #- ./nginx/server.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    networks:
      - server_net
  php:
    build: ./php # it specifies the path of Dockerfile (need to run docker-compose build). No need to add image tag
    working_dir: /usr/share/nginx/html
    volumes:
      - ./www:/usr/share/nginx/html
    networks:
      - server_net

networks:
  server_net:

